### PR TITLE
Trakt authentication

### PR DESCRIPTION
**Pull request by ghost**
this is not really ready to be pulled just yet.. A couple more things needs to be done -- but this is fully functional as I tested by deploying this branch of radarrAPI on my localmachine and modifying my radarr client to use the correct endpoints using a radarr_test app registered at trakt.tv

the client secret for radarr_test is exposed in this code but that is just temporary as  we should store the client_secret for radarr somewhere on the server outside the sourceTree so it is not exposed on git.

After this feature is finished I will be deleting radarr_test from trakt API registration.

also the trakt redirect uri needs to be set properly, in order for this to work.... when we are ready to deploy.. we should make sure these match. I believe it should be:

https://radarr.aeonlucid.com/authorize/trakt

Lastly, the state should not be sending target, but rather a unique and unguessable state should be generated.. this generated state should be stored along with target..

I am just initiating this pull request so @AeonLucid @onedr0p and @galli-leo can see where we're at and help me complete the remaining parts...

also when i had radarrAPI deployed on my machine for testing it only seemed to work with http.. but it should be https.. there are a couple spots where this might need to be changed.

once this is properly deployed radarr trakt authentication will need to be updated to reflect the proper endpoints.

### CODE REVIEW

**Comment by geogolem** [comment]
i realized storing the target and state wont really make a difference... so it seems fine the way it is.. I think.

**Comment by onedr0p** [comment]
Anything left to get this going? I believe we were just waiting on the API here.

**Comment by AeonLucid** [comment]
I will try to finish implement this PR and fix it up by tomorrow @onedr0p.

**Comment by AeonLucid** [comment]
Added https://github.com/Radarr/RadarrAPI/commit/26300aae637b01eb0448cc5e2c1f7cc8f0f061b8

**Pull request closed without merging**
